### ISSUE TITLE
consider removing on-disk caching from this spec?

### ISSUE THREAD

**Issue by isaacs** [bmeck/UnambiguousJavaScriptGrammar#10]
I have concerns about disk caching in general, having lived through the three hells of DLL, php's APC, and the ~/.npm folder, all of which provide valuable services, but can at times become corrupted, leading to a superstitious habit of blowing away the cache.  This superstition is harmful for 3 reasons: 1, it typically does not solve problems, but only makes the program slower, but (2) it _does_ work _sometimes_ for _some_ kinds of problems, so it's a thing you have to know about, which means that (3), experienced devs try it all the time, and it's yet another thing that newbs have to learn.  (And they probably learn the superstition without learning the types of problems it solves, maybe that's problem number 4?  [Among the problems caused by on disk caching are such items as...](https://www.youtube.com/watch?v=7WJXHY2OXGE))

That's not to say an on-disk module bytecode cache is a bad idea.  Judicious use of on-disk caching can make slow things much faster.  But does it belong in this spec?  It seems like a distraction here, and I think it's best to just leave it up to the host to optimize parsing however they see fit.  Then the caching discussion can happen over in node CTC land.

**Comment by jdalton** [comment]
I hear ya. It was necessary to avoid upfront knee-jerk concerns over performance.
The proposal words it as a recommendation and not mandated.

**Comment by jdalton** [comment]
I updated the text to be more wiggly, https://github.com/bmeck/UnambiguousJavaScriptGrammar/commit/7ecfa12d4067d52444f85c67d115f300f7e4099e.

**Comment by isaacs** [comment]
In my opinion, knee-jerk performance responses require benchmarks.  Parsing startup time is extremely negligible, and it's not at all clear that adding an extra filesystem lookup will make it go faster in many cases.

**Comment by bmeck** [comment]
@trevnorris did a little bit on this, but real world benches are generally diff than micro

**Comment by isaacs** [comment]
It'd really only matter for relatively large command-line applications.  (Servers don't matter, because they start up only very rarely.)

If it doesn't make a perceptible difference to something like npm or ember-cli, it's probably not worth the added complexity.

**Comment by jdalton** [comment]
Cache section was de-emphasized at https://github.com/bmeck/UnambiguousJavaScriptGrammar/commit/fd0936e1fdf30b86534b8e99fe1e9bf0c5a9ea21.
Investigations by @trevnorris showed that, even without caching, perf wasn't a significant issue.

**Comment by jdalton** [comment]
Investigations by @trevnorris showed that perf wasn't a significant issue without caching.
