### ISSUE TITLE
import / export s/statement/declaration

### ISSUE THREAD

**Issue by leobalter** [bmeck/UnambiguousJavaScriptGrammar#11]
To avoid any distractions, it would be good to rephrase the proposal to use import or export declarations instead of calling them statements, as that's what [they technically are in the specs](https://tc39.github.io/ecma262/#prod-ModuleItem)

**Comment by jmm** [comment]
The distinction between _statement_ and _declaration_ in the spec is pretty hazy. Sometimes they're used sort of interchangeably. I guess it probably boils down to something like all declarations are statements, but not vice versa. I asked **allenwb** about it [here](https://github.com/tc39/ecma262/pull/341#issuecomment-179522580) (_statement vs declaration_) and his response follows. The spec isn't even really consistent internally. For example, in [15.2.1.16 Source Text Module Records](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-source-text-module-records) it says _export statement_.
