### ISSUE TITLE
JSCS double parses?

### ISSUE THREAD

**Issue by markelog** [bmeck/UnambiguousJavaScriptGrammar#13]
> JSCS double parses, first as the Script goal, then as the Module goal

What do you mean by that? Where exactly do we do that?

**Comment by jdalton** [comment]
Hi @markelog!

I got that bit from @mikesherov:

> Currently, JSCS double parses, first as script and failing that, falls back to module. Would be nice if JSCS could parse as module first, and fall back to script considering that modules will grow as script shrinks. Can't do that unless there is a failure case for modules. Without UJG, module-first would incorrectly identify most scripts...

I'll let you two hash it out.

**Comment by mikesherov** [comment]
At one point we were doing that, no?

**Comment by mikesherov** [comment]
Am I not remembering correctly?

**Comment by markelog** [comment]
> At one point we were doing that, no?

I don't think so, not aware of any code like that

**Comment by jdalton** [comment]
No worries, I've removed that bit of the blurb.
