### ISSUE TITLE
inline modules in browsers

### ISSUE THREAD

**Issue by teppeis** [bmeck/UnambiguousJavaScriptGrammar#14]
If this spec is accepted, inline modules in browsers require `export {}` ?

``` html
<script type="module">
console.log('hello');
export {}
</script>
```

With `type="module"`, it's a module clearly.
Extra `export {}` seems redundant.

**Comment by bmeck** [comment]
Yes, it would be required. Redundant, maybe, but makes it explicit on the JS source text (right now HTML source text is explicit/unambiguous, not JS).

**Comment by jdalton** [comment]
@teppeis By "If this spec is accepted" you mean the proposed ECMAScript spec change, then likely yes.
That said, UnambiguousJavaScriptGrammer can be a Node specific addition. We'll be meeting with the TC39 in July to discuss it further. Regardless, with this proposal existing workflows of code coming from Node to the browser will continue to work and ES modules of Node could work with `type="module"` in the browser.

**Comment by teppeis** [comment]
@bmeck @jdalton thanks. IMO extra `export {}` is unacceptable boilerplate tax on non-Node users.
Node specific extension is better for both Node and browsers.

**Comment by bmeck** [comment]
@teppeis and I heavily will argue against any node specific extension. The lack of any import/export is an edge case that produces ambiguity (how many modules plan on not importing/exporting anything?). I see no reason to keep ambiguity in light of this if it hurts the rest of modules (not just Node).

**Comment by ljharb** [comment]
@teppeis it's only a boilerplate tax on people making modules that solely have side effects - and these people are precisely the ones who _should_ endure such a tax.

**Comment by teppeis** [comment]
@bmeck @ljharb In browsers, no-import/export script (including inline module) is an edge case?

**Comment by bmeck** [comment]
@teppeis in most environments side-effect only modules are an edge case. How many pieces of browser code don't rely on a dependency like `import $ from "jQuery";`, and those that don't have any dependencies, how many don't export anything?

**Comment by ljharb** [comment]
@teppeis you might indeed have one module that imports everything else and has side effects - and it is useful to require that that entry point - which is 1 out of many many modules included on that page - has something extra to explicitly denote it. However, as long as it imports something, it wouldn't require any additional boilerplate.

In other words, yes, a module that imports nothing and exports nothing is an edge case, even in browsers.

**Comment by teppeis** [comment]
@bmeck @ljharb I have some tiny sites and the each site has only one small JS file or inline script. I want to load then as ES Modules not for import/export, but for non global scope, strict mode and undefined this. Because [module is the new script](https://twitter.com/domenic/status/743981311568785408).

**Comment by bmeck** [comment]
I would disagree on module is the new script, especially if new goals come along after it https://twitter.com/awbjs/status/744701901560651777

**Comment by teppeis** [comment]
@bmeck I found out the root cause of a difference of opinion. The original question is resolved. Thanks for conversation!
