### ISSUE TITLE
Assume Module goal when importing local files

### ISSUE THREAD

**Issue by davidmarkclements** [bmeck/UnambiguousJavaScriptGrammar#15]
It makes sense to assume Script goal for third party modules, due to there currently being way more CJS modules but if a project is choosing es6 module for the entry point, then it seems very
likely that local libs will be es6 modules too

``` js
import foo from 'foo' // assume Script first (if no 'module' field in package.json)
import bar from './bar.js' // assume Module first
```

**Comment by jdalton** [comment]
Hi @davidmarkclements!

I think there's room for this as a progression of the proposal. At the moment I'd like to keep things simple. Since there's no explicit opt-in to a preferred parse goal I'd like to avoid making assumptions up front.
