### ISSUE TITLE
What happens when "module" goal is intended but programmer forgets the 'export' keyword?

### ISSUE THREAD

**Issue by yortus** [bmeck/UnambiguousJavaScriptGrammar#17]
This proposal disambiguates the `"script"` and `"module"` goals by requiring something _explicit_ to be present to signal the intent to define a module. But it does not require anything explicit to signal the intent to define a script (merely the _absence_ of what defines a module).

Just curious if there's been any discussion about what this means in the face of the fairly simple/common programmer error of intending to write a module but forgetting to `export` the member(s).

Under this proposal (and supposing `"module"` is the preferred goal), such a module will fail to parse with the "module" goal, so it falls back to the "script" goal and parses without error. Then runtime errors ensue until the programmer figures out their mistake. The error messages don't point to the real problem of the forgotten `export`.

I like the wording of the _problem_ in this proposal (same source code gives different results). And the solution definitely disambiguates the two grammars. But it doesn't offer much to disambiguate the programmer's _intent_, because there's no way to tell whether a valid `"script"` file was indented as such, or was intended to be a module but an `export` keyword was overlooked (easy to do).

By analogy, JavaScript operators have an _unambiguous implementation_, so that `2 + '1' === '21'` and `2 - '1' === 1` on all compliant platforms. But that doesn't address the problem that the user likely didn't intend that operation.

**Comment by jdalton** [comment]
Hi @yortus!

The proposal does call out that a developer can specify their preferred goal in a package.json field. Then, if they choose `'module'`, as things are refactored, and they come into a situation without an `import` or `export`, it would trigger an error (this is also covered in the proposal).

**Comment by yortus** [comment]
@jdalton thanks. Where in the proposal does it say this? I've read back over it, and still get a different impression of the proposed approach, so it's possibly unclear. In particular this is what prompted my question above:

> If there is a parse error that may allow another goal to parse, then parse as the other goal, and so on.

That doesn't sound like the user sees any triggered error, just that the implementation silently goes on to try the other goal. That, in my understanding, would lead to the scenario above.

If forgetting an `export` in a module does indeed trigger an error to the user (rather than just reparsing as a script), could this possibly be made a little clearer in the proposal?

**Comment by jdalton** [comment]
The line or two above:

> A package opts-in to the Module goal by specifying "module" as the parse goal field (name not final) in its package.json. 

Then in the [operation](https://github.com/bmeck/UnambiguousJavaScriptGrammar#operation) section:

> 1. If a package parse goal is specified, then
>    1. Let `goal` be the resolved parse goal.
>    2. Call `Parse(source, goal, true)` and return.

**Comment by yortus** [comment]
OK I see the interpretation you mean now. However please consider that the language in both of those sections admits multiple interpretations. At a minimum please consider modifying step 2 under [operation](https://github.com/bmeck/UnambiguousJavaScriptGrammar#operation) to "_Else_ Fallback to multiple parse.", similarly to how 2.i. starts with 'If' and 2.ii. starts with 'Else'. Otherwise it appears that step 2 (the _fallback_) may also occur if step 1 fails.

**Comment by jdalton** [comment]
~~I rather not break it into an `2 Else` block.~~ The `If` in step one ends with a `return` so there's no chance of recovery it either errors or returns.

I added a clarifying "Else" https://github.com/bmeck/UnambiguousJavaScriptGrammar/commit/b547379e2a8d6999528597d1cc1a8c20e74a0904.
