### ISSUE TITLE
Updates of this proposal

### ISSUE THREAD

**Issue by sheerun** [bmeck/UnambiguousJavaScriptGrammar#18]
Hey!

Just curious what's the status of this proposal. Could you leave this issue open and post updates?

**Comment by jdalton** [comment]
See https://github.com/bmeck/UnambiguousJavaScriptGrammar#proposal-accepted.
Head to the [node-eps repo](https://github.com/nodejs/node-eps) for further updates.

**Comment by ilkkao** [comment]
There was a TC39 meeting few weeks ago. This proposal was not discussed there?

**Comment by bmeck** [comment]
@ilkkao it was not, the timing of this proposal coming up was a bit late in order for us to be prepared to talk about it. Other talks about modules were held offline that have large impact to interop and I am trying to work those out prior to coming back to this.

**Comment by ilkkao** [comment]
Thanks for the info. As expected, standardization will take time.

**Comment by jedwards1211** [comment]
One of the links was broken, see now: https://github.com/nodejs/node-eps/blob/master/002-es-modules.md
