### ISSUE TITLE
Why actually export something to satisfy the parsing goal?

### ISSUE THREAD

**Issue by jmm** [bmeck/UnambiguousJavaScriptGrammar#3]
Can you comment on why you decided to advise actually exporting something (`export default null`) as opposed to a no-op that satisfies the parsing goal (`export {}`)? (I'm not entirely sure why, but I believe that's valid.) Do you think it more clearly indicates intent?

Thanks!

**Comment by jdalton** [comment]
> Can you comment on why you decided to advise actually exporting something (`export default null`) as opposed to a no-op that satisfies the parsing goal (`export {}`)? 

I think `export default null` is a bit more descriptive but they both accomplish the same goal.
I could add a shout out to both.

**Comment by jmm** [comment]
Thanks for the feedback. I think I personally would be a bit more inclined to do `export {}` (or something like `export { /* noop */ }` if I wanted to be more explicit), but since there's no hard requirement in terms of that I'll be keeping an eye out for what conventions (like your suggestion) emerge or get traction if this proposal moves forward. I don't know off the top of my head if there'd ever be any other reason to do `export default null` (though I'd expect it to be rare).

**Comment by jdalton** [comment]
>  I think I personally would be a bit more inclined to do export {}

 I think you're right. I'll make the correction.

**Comment by jmm** [comment]
Ok cool. That makes sense to me right now, but if some other convention turns out to be better I'd be all for it.
