### ISSUE TITLE
Add line to clarify why a ECMAScript spec change is needed.

### ISSUE THREAD

**Issue by jdalton** [bmeck/UnambiguousJavaScriptGrammar#5]
The ECMAScript spec allows for Node to restrict ES modules to having an `import` and or `export` by way of it not being an [forbidden extension](http://www.ecma-international.org/ecma-262/6.0/#sec-forbidden-extensions). The proposal should clarify why, with the wiggle room already there, a spec change is needed.

**Comment by bmeck** [comment]
Node lacks desire to only partially implement ES modules, then we get to threads like this: https://twitter.com/awbjs/status/743171126214307840 where TC39 members are trying to say node doesn't do things correctly.
