### ISSUE TITLE
Expand problem section for needing a modules.root.

### ISSUE THREAD

**Issue by jdalton** [bmeck/UnambiguousJavaScriptGrammar#6]
The current [section](https://github.com/bmeck/UnambiguousJavaScriptGrammar#problem-2) has

> ##### Problem
> 
> Node needs a way for developers to ship both CJS and ES modules in a single package.

We should flesh out why the need is there. Or answer the question of:

> Why shouldn't package authors who want CJS compatibility just have packages of transpiled code, as they do now?

What's the carrot for package authors?
Are subtle differences where transpilation fails to align with the specification a concern?

**Comment by bmeck** [comment]
Biggest carrot is the fact that browsers don't have interop story yet. If I have a browser app using npm I need a way to ship a purely ES modules package, but if I want to work on Node I want CJS modules to have compat with older Node versions.

Problem is around browser having no interop story, its kinda the inverse of supporting legacy, its supporting the breakage of backwards compat.

**Comment by bmeck** [comment]
I would swap the view to the fact that browsers don't have interop story.

**Comment by jdalton** [comment]
In those cases I think simply transpiling is a better option as it ensures consistent behavior in old and new environments. Since features like this introduce some complexity and can be added at a later time I think we should opt for keeping the proposal simple with the option of expanding later.

**Comment by bmeck** [comment]
Can't load transpiled code into browser under current plans [using type=module].

**Comment by jdalton** [comment]
Sure as normal scripts, it's transpiled.

**Comment by bmeck** [comment]
But no way to handle these as dependencies in same way via `import`. Would need bundler to unwind the deps into `<script src="...">` but I don't see how we could preserve timing that way.

**Comment by jdalton** [comment]
There are already established workflows for dealing with Node to browser code (transpiling, bundling, etc.). This proposal wouldn't diminish those existing paths. So folks wanting back compat can continue to use those paths.

**Comment by bmeck** [comment]
I don't understand, what are you suggesting for browser `import "cjs"`? Maybe a chat about this would be easier?

**Comment by bmeck** [comment]
Chat notes:

J: `type=module` will only be able to load ES modules, no plan for interop. Use browserify etc. and non module script tag.
B: being unable to use any of existing CJS with `type=module` is prohibitive: people don't always control if their deps have CJS somewhere deep in the dep graph.

**Comment by jdalton** [comment]
Ok, after some discussion. We'll try keeping things simple to start and drop `modules.root`. This doesn't prevent `modules.root` from being added later as it has perks beyond ES modules. This also doesn't tackle the browser's lack of a compat story.
